# Generated by Django 5.2.9 on 2025-12-07 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_slug', models.SlugField(help_text='ID único do curso (ex: engenharia-software)', max_length=100, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('duracao', models.CharField(help_text='Ex: 4 anos, 6 semestres', max_length=100)),
                ('area', models.CharField(help_text='Ex: Engenharia, Ciências Humanas', max_length=200)),
                ('avaliacao_geral', models.FloatField(default=0.0, help_text='Avaliação de 0 a 5')),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-avaliacao_geral'],
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_slug', models.SlugField(help_text='ID único da instituição (ex: puc-rio)', max_length=100, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='instituicoes/')),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=300)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('avaliacao_geral', models.FloatField(default=0.0, help_text='Avaliação de 0 a 5')),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['-avaliacao_geral'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=10)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='professores.curso')),
            ],
            options={
                'verbose_name': 'Comentário de Curso',
                'verbose_name_plural': 'Comentários de Cursos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='professores.instituicao'),
        ),
        migrations.CreateModel(
            name='ComentarioInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=10)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='professores.instituicao')),
            ],
            options={
                'verbose_name': 'Comentário de Instituição',
                'verbose_name_plural': 'Comentários de Instituições',
                'ordering': ['-criado_em'],
            },
        ),
    ]
