# Generated by Django 6.0 on 2025-12-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "professores",
            "0002_curso_instituicao_comentariocurso_curso_instituicao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="nota",
            field=models.IntegerField(default=5, help_text="Nota de 1 a 5"),
        ),
    ]
